#!/bin/bash

status-set waiting "waiting for Keystone credentials"

if [ -z "$(relation-get service_password)" ]; then
  exit 0;
fi

juju-log "$(relation-get --format=json)"

status-set maintenance "writing 'novarc' file"

cat > /root/.keystone_auth <<EOF
OS_AUTH_URL=$(relation-get service_hostname):$(relation-get service_port)/v2.0
OS_TENANT_NAME=$(relation-get service_tenant_name)
OS_USERNAME=$(relation-get service_username)
OS_REGION=$(relation-get service_region)
OS_PASSWORD=$(relation-get service_password)
EOF

status-set active "ready to benchmark"
